version: "3.7"

services: 
    redis-master:
        build: 
            context: .
            dockerfile: dockerfiles/master.Dockerfile
        container_name: redis-master-sentinel
        volumes: 
            - ./data/master:/data
        ports: 
            - 6379:6379
        env_file: .env
        # restart: always
    
    redis-slave:
        build: 
            context: .
            dockerfile: dockerfiles/slave.Dockerfile
        container_name: redis-slave-sentinel
        ports: 
            - 6380:6379
        volumes: 
            - ./data/slave:/data
        env_file: .env
        # restart: always
    
    redis-sentinel:
        build: 
            context: .
            dockerfile: dockerfiles/sentinel.Dockerfile
        container_name: redis-sentinel-sentinel
        env_file: .env
        ports: 
            - 26379:26379
    #     # restart: always

    redis-commander:
        build: 
            context: .
            dockerfile: dockerfiles/client.Dockerfile
        container_name: redis-commander-sentinel
        ports: 
            - 8081:8081
        env_file: .env
    #     restart: always
