version: "3.7"

services: 
    redis-master:
        build: 
            context: .
            dockerfile: dockerfiles/master.Dockerfile
        container_name: redis-master-sentinel
        volumes: 
            - ./data/master:/data
        ports: 
            - 6379:6379
        env_file: .env
        # restart: always
    
    redis-slave:
        build: 
            context: .
            dockerfile: dockerfiles/slave.Dockerfile
        container_name: redis-slave-sentinel
        ports: 
            - 6380:6379
        volumes: 
            - ./data/slave:/data
        env_file: .env
        # restart: always
    
    # redis-sentinel:
    #     build: 
    #         context: .
    #         dockerfile: sentinel.Dockerfile
    #     container_name: redis-sentinel-sentinel
    #     ports: 
    #         - 26379:26379
    #     # restart: always

    # redis-commander:
    #     image: rediscommander/redis-commander:latest
    #     container_name: redis-commander-sentinel
    #     ports: 
    #         - 8081:8081
    #     environment:
    #         SENTINEL_HOST: 192.168.4.91
    #         SENTINEL_NAME: master
    #         REDIS_PASSWORD: f81e8c52d71acd9d5259c47aa449810030d882d0d120e32a45039a86c97f6f9c
    #     restart: always
