version: "3.7"

services: 
    redis-master:
        image: redis:6-alpine
        container_name: redis-master
        networks: 
            redis-sentinel:
        volumes: 
            - ./data/master:/data
            - ./conf/master.conf:/usr/local/etc/redis/redis.conf
        command: redis-server /usr/local/etc/redis/redis.conf
    
    redis-slave:
        image: redis:6-alpine
        container_name: redis-slave
        networks: 
            redis-sentinel:
        volumes: 
            - ./data/slave:/data
            - ./conf/slave.conf:/usr/local/etc/redis/redis.conf
        command: redis-server /usr/local/etc/redis/redis.conf


networks: 
    redis-sentinel:
        name: redis-sentinel